# Generated by Django 2.1.7 on 2019-02-27 17:08
import json

from django.db import migrations, models
from server.settings import APPS_CORE_DIR


def create_initial_currencies(apps, schema_editor):
    Currency = apps.get_model('core', 'Currency')
    with open(APPS_CORE_DIR + '/initial_data/currencies.json') as f:
        currencies = [curr['code'] for curr in json.loads(f.read())]

    for currency_code in currencies:
        Currency.objects.create(code=currency_code)


def reverse(apps, schema_editor):
    # No need to do anything, because the table will be deleted anyway
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RunPython(create_initial_currencies, reverse),
    ]
