# Generated by Django 2.1.7 on 2019-02-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'currencies'},
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(default='EUR', on_delete=django.db.models.deletion.CASCADE, to='core.Currency'),
        ),
    ]
